language: nix

matrix:
  include:
    - env: GHCVER=ghc7102
    - env: GHCVER=ghc7103
    - env: GHCVER=ghc801
    - env: GHCVER=ghc802
  allow_failures:
    - env: GHCVER=ghc742
    - env: GHCVER=ghc763
    - env: GHCVER=ghc783
    - env: GHCVER=ghc784
    - env: GHCVER=ghcHEAD

before_install:
 - nix-channel --list
 - nix-channel --update

script:
 - nix-build -A stripe-haskell --argstr compiler $GHCVER
